server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages #사용할 다국어 파일의 이름을 messages로 정의

#  security:
#    user:
#      name: user
#      password: 1234  #SpringSecurity의 유저와 비밀번호 설정

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #Swagger 3.0이 실행되지 않을 때 변경하는 세팅

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:testdb  #접속 URL
    username: sa  # 사용자 이름 (로그인 시 사용)
    password:   # 사용자 암호 (로그인 시 사용)

  jpa:
    show-sql: true
    defer-datasource-initialization: true #

  h2:
    console:
      enabled: true